In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
%cd /content/drive/MyDrive/Hypertension_Final_Project/cleaned_file/2017

/content/drive/MyDrive/Hypertension_Final_Project/cleaned_file/2017

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
pd.options.display.float_format = '{:20,.2f}'.format

In [ ]:
year = 2017

In [ ]:
BASE_PATH = "/content/drive/MyDrive/Hypertension_Final_Project/data_" + str(year) + '/'

In [ ]:
BASE_PATH

'/content/drive/MyDrive/Hypertension_Final_Project/data_2017/'

# Diary View

In [ ]:
d1 = pd.read_sas(filepath_or_buffer = BASE_PATH + 'DR1TOT_J.XPT')
d1.loc[(d1['WTDRD1']<0.01),'WTDRD1']=np.nan
d1.loc[(d1['WTDR2D']<0.01),'WTDR2D']=np.nan
d1.loc[(d1['DR1DRSTZ']==2),'DR1DRSTZ']=np.nan
d1.loc[(d1['DR1DRSTZ']==5),'DR1DRSTZ']=np.nan
d1.loc[(d1['DR1LANG']==3),'DR1LANG']=2
d1.loc[(d1['DR1LANG']==5),'DR1LANG']=4
d1.loc[(d1['DR1LANG']==6),'DR1LANG']=4
d1.loc[(d1['DBQ095Z']==99),'DBQ095Z']=np.nan
d1.loc[(d1['DBD100']==9),'DBD100']=np.nan
d1.loc[(d1['DRQSPREP']==9),'DRQSPREP']=np.nan
# d1.loc[(d1['DR1TWS']==99),'DR1TWS']=np.nan
d1.loc[(d1['DRD340']==9),'DRD340']=np.nan
d1.loc[(d1['DRD340']==7),'DRD340']=np.nan

d1=d1.rename({'DRABF':'Breast-fed_infantdummy','DRDINT':'Number_of_days_of_intake_dummy','DR1LANG':'language_dummy','DBQ095Z':'salt_type_dummy','DBD100':'salt_freq_dummy','DRQSPREP':'salt_prep_dummy','DRQSDIET':'special_diet_dummy','DR1TWS':'tap_water_source_dummy','DRD340':'Shellfish_eaten_1_dummy','DRD350A':'clams_eaten_1_dummy','DRD350B':'crabs_eanten_1_dummy','DRD350C':'crayfish_eaten-1_dummy','DRD350D':'lobsters+eaten_1_dummy','DRD350E':'mussels_eaten_1_dummy','DRD350F':'oysters_eaten_1_dummy'})
d1=d1.drop(columns={'DR1EXMER','DR1DAY', 'DRQSDT1','DRQSDT2','DRQSDT3','DRQSDT4','DRQSDT5','DRQSDT6','DRQSDT7','DRQSDT8','DRQSDT9','DRQSDT10','DRQSDT91','DR1_300','DRD370JQ','DRD370KQ','DRD370LQ','DRD370NQ','DRD370OQ','DRD370PQ','DRD370QQ','DRD370RQ','DRD370SQ','DRD370UQ','DRD370V'})
d1.to_csv('cleaned_dietary_data.csv')

/usr/local/lib/python3.7/dist-packages/pandas/io/sas/sas_xport.py:475: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  df[x] = v

In [ ]:
d1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8704 entries, 0 to 8703
Columns: 143 entries, SEQN to DRD370U
dtypes: float64(143)
memory usage: 9.6 MB

In [ ]:
d2 = pd.read_sas(filepath_or_buffer = BASE_PATH + 'DR2TOT_J.XPT')
d2.loc[(d1['WTDRD1']<0.01),'WTDRD1']=np.nan
d2.loc[(d1['WTDR2D']<0.01),'WTDR2D']=np.nan
d2.loc[(d1['DR1DRSTZ']==2),'DR1DRSTZ']=np.nan
d2.loc[(d1['DR1DRSTZ']==5),'DR1DRSTZ']=np.nan
d2.loc[(d1['DR1LANG']==3),'DR1LANG']=2
d2.loc[(d1['DR1LANG']==5),'DR1LANG']=4
d2.loc[(d1['DR1LANG']==6),'DR1LANG']=4
d2.loc[(d1['DBQ095Z']==99),'DBQ095Z']=np.nan
d2.loc[(d1['DBD100']==9),'DBD100']=np.nan
d2.loc[(d1['DRQSPREP']==9),'DRQSPREP']=np.nan
# d2.loc[(d1['DR1TWS']==99),'DR1TWS']=np.nan
d2.loc[(d1['DRD340']==9),'DRD340']=np.nan
d2.loc[(d1['DRD340']==7),'DRD340']=np.nan
d2=d2.rename({'DRABF':'Breast-fed_infantdummy','DRDINT':'Number_of_days_of_intake_dummy','DR1LANG':'language_dummy','DBQ095Z':'salt_type_dummy','DBD100':'salt_freq_dummy','DRQSPREP':'salt_prep_dummy','DRQSDIET':'special_diet_dummy','DR1TWS':'tap_water_source_dummy','DRD340':'Shellfish_eaten_1_dummy','DRD350A':'clams_eaten_1_dummy','DRD350B':'crabs_eanten_1_dummy','DRD350C':'crayfish_eaten-1_dummy','DRD350D':'lobsters+eaten_1_dummy','DRD350E':'mussels_eaten_1_dummy','DRD350F':'oysters_eaten_1_dummy'})
d2.to_csv('cleaned_dietary_data_2.csv')

# Hypertension Identification

## Blood Pressumre

In [ ]:
# read sas file
blood_pressure = pd.read_sas(filepath_or_buffer = BASE_PATH + 'BPX.XPT')
# obtain Systolic_BP and Diastolic_BP data
blood_pressure_columns = ['SEQN', 'BPXPLS', 'BPXSY1', 'BPXDI1', 'BPXSY2', 'BPXDI2', 'BPXSY3', 'BPXDI3', 'BPXSY4', 'BPXDI4']
blood_pressure = blood_pressure[blood_pressure_columns]
# calculate average Systolic_BP and Diastolic_BP (average all 4 tests)
blood_pressure['Systolic_BP'] = blood_pressure.loc[:,['BPXSY1', 'BPXSY2', 'BPXSY3', 'BPXSY4']].mean(axis = 1)
blood_pressure['Diastolic_BP'] = blood_pressure.loc[:,['BPXDI1', 'BPXDI2', 'BPXDI3', 'BPXDI4']].mean(axis = 1)
# obtain clean the BP data
blood_pressure_final = blood_pressure.loc[:,['SEQN', 'Systolic_BP', 'Diastolic_BP']]

## Hypertension (Questionnaire)

In [ ]:
# read questionnaire data
Hypertension = pd.read_sas(filepath_or_buffer = BASE_PATH + 'BPQ.XPT')
# preprocess the data
Hypertension_columns = ['SEQN', 'BPQ020', 'BPQ050A']
Hypertension = Hypertension[Hypertension_columns]

Told_High_blood_pressure
- 0：not been told that s/he has hypertension, also called high blood pressure
- 1：been told that s/he has hypertension, also called high blood pressure

In [ ]:
Hypertension.loc[Hypertension['BPQ020'] == 2, 'Told_High_blood_pressure_dummy'] = 0
Hypertension.loc[Hypertension['BPQ020'] == 1, 'Told_High_blood_pressure_dummy'] = 1

In [ ]:
# Taking Medicine for HBP
Hypertension.loc[Hypertension['BPQ050A'] == 2, 'Taking_Medicine_for_HBP_dummy'] = 0
Hypertension.loc[Hypertension['BPQ050A'] == 1, 'Taking_Medicine_for_HBP_dummy'] = 1

In [ ]:
Hypertension.drop(columns = ['BPQ020', 'BPQ050A'], inplace = True)
Hypertension_combine = Hypertension.merge(blood_pressure_final, on = 'SEQN', how = 'outer')

In [ ]:
Hypertension_final = Hypertension_combine[~((Hypertension_combine['Taking_Medicine_for_HBP_dummy'].isnull()) & (Hypertension_combine['Systolic_BP'].isnull()))]

In [ ]:
Hypertension_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7954 entries, 0 to 10423
Data columns (total 5 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   SEQN                            7954 non-null   float64
 1   Told_High_blood_pressure_dummy  6536 non-null   float64
 2   Taking_Medicine_for_HBP_dummy   1937 non-null   float64
 3   Systolic_BP                     7818 non-null   float64
 4   Diastolic_BP                    7818 non-null   float64
dtypes: float64(5)
memory usage: 372.8 KB

Hypertension
- Systolic_BP > 130
- Diastolic_BP > 80
- Taking Medicine for HBP

In [ ]:
Hypertension_final.loc[(Hypertension_final['Systolic_BP'] > 130) | (Hypertension_final['Diastolic_BP'] > 80) | (Hypertension_final['Taking_Medicine_for_HBP_dummy'] == 1), 'Hypertension_dummy'] = 1
Hypertension_final.loc[(Hypertension_final['Systolic_BP'] <= 130) | (Hypertension_final['Diastolic_BP'] <= 80), 'Hypertension_dummy'] = 0

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1684: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = infer_fill_value(value)
/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [ ]:
Hypertension_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7954 entries, 0 to 10423
Data columns (total 6 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   SEQN                            7954 non-null   float64
 1   Told_High_blood_pressure_dummy  6536 non-null   float64
 2   Taking_Medicine_for_HBP_dummy   1937 non-null   float64
 3   Systolic_BP                     7818 non-null   float64
 4   Diastolic_BP                    7818 non-null   float64
 5   Hypertension_dummy              7943 non-null   float64
dtypes: float64(6)
memory usage: 435.0 KB

In [ ]:
Hypertension_final = Hypertension_final[~Hypertension_final['Hypertension_dummy'].isnull()]

In [ ]:
Hypertension_final['Hypertension_dummy'].value_counts()

0.00    7247
1.00     696
Name: Hypertension_dummy, dtype: int64

In [ ]:
Hypertension_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7943 entries, 0 to 10423
Data columns (total 6 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   SEQN                            7943 non-null   float64
 1   Told_High_blood_pressure_dummy  6525 non-null   float64
 2   Taking_Medicine_for_HBP_dummy   1926 non-null   float64
 3   Systolic_BP                     7818 non-null   float64
 4   Diastolic_BP                    7818 non-null   float64
 5   Hypertension_dummy              7943 non-null   float64
dtypes: float64(6)
memory usage: 434.4 KB

In [ ]:
Hypertension_final[Hypertension_final['Told_High_blood_pressure_dummy'] == 0]['Hypertension_dummy'].value_counts()

0.00    4081
1.00     250
Name: Hypertension_dummy, dtype: int64

In [ ]:
Hypertension_final[Hypertension_final['Told_High_blood_pressure_dummy'] == 1]['Hypertension_dummy'].value_counts()

0.00    1752
1.00     442
Name: Hypertension_dummy, dtype: int64

In [ ]:
Hypertension_final.to_csv('Hypertension_final.csv')

In [ ]:
Hypertension_SEQN = Hypertension_final['SEQN']

In [ ]:
Hypertension_SEQN.to_csv('Hyper_SEQN.csv')

# demographic

In [ ]:
demographic = pd.read_sas(filepath_or_buffer = BASE_PATH + 'DEMO.XPT')

# respondents that were both interviewed and examined
demographic  = demographic[demographic['RIDSTATR'] == 2]

demographic.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10253 entries, 0 to 10536
Data columns (total 43 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SEQN      10253 non-null  float64
 1   SDDSRVYR  10253 non-null  float64
 2   RIDSTATR  10253 non-null  float64
 3   RIDEXMON  10253 non-null  float64
 4   RIAGENDR  10253 non-null  float64
 5   RIDAGEYR  10253 non-null  float64
 6   RIDAGEMN  9857 non-null   float64
 7   RIDAGEEX  9855 non-null   float64
 8   RIDRETH1  10253 non-null  float64
 9   DMQMILIT  6554 non-null   float64
 10  DMDBORN2  10253 non-null  float64
 11  DMDCITZN  10246 non-null  float64
 12  DMDYRSUS  1932 non-null   float64
 13  DMDEDUC3  2531 non-null   float64
 14  DMDEDUC2  6059 non-null   float64
 15  DMDSCHOL  2296 non-null   float64
 16  DMDMARTL  6059 non-null   float64
 17  DMDHHSIZ  10253 non-null  float64
 18  DMDFMSIZ  10253 non-null  float64
 19  INDHHIN2  10189 non-null  float64
 20  INDFMIN2  10203 non-null  float64
 21  INDFMPIR  9311 non-null   float64
 22  RIDEXPRG  1377 non-null   float64
 23  DMDHRGND  10253 non-null  float64
 24  DMDHRAGE  10253 non-null  float64
 25  DMDHRBR2  10006 non-null  float64
 26  DMDHREDU  10006 non-null  float64
 27  DMDHRMAR  10130 non-null  float64
 28  DMDHSEDU  5349 non-null   float64
 29  SIALANG   10253 non-null  float64
 30  SIAPROXY  10250 non-null  float64
 31  SIAINTRP  10253 non-null  float64
 32  FIALANG   10207 non-null  float64
 33  FIAPROXY  10207 non-null  float64
 34  FIAINTRP  10207 non-null  float64
 35  MIALANG   7359 non-null   float64
 36  MIAPROXY  7359 non-null   float64
 37  MIAINTRP  7358 non-null   float64
 38  AIALANG   5488 non-null   float64
 39  WTINT2YR  10253 non-null  float64
 40  WTMEC2YR  10253 non-null  float64
 41  SDMVPSU   10253 non-null  float64
 42  SDMVSTRA  10253 non-null  float64
dtypes: float64(43)
memory usage: 3.4 MB

In [ ]:
demo_columns = ['SEQN', 'SDDSRVYR', 'RIAGENDR', 'RIDAGEYR', 'RIDRETH1', 'DMDBORN2', 'DMDMARTL', 'DMDEDUC3', 'DMDEDUC2', 'DMDHREDU', 'INDFMIN2', 'INDFMPIR']
demographic = demographic[demo_columns]

## Marital_Status
- 1: Married/Living with partner
- 2: Widowed/Divorced/Separated
- 3: Never Married

In [ ]:
demographic.loc[((demographic['DMDMARTL'] == 1) | (demographic['DMDMARTL'] == 6)), 'Marital_Status_dummy'] = 1
demographic.loc[((demographic['DMDMARTL'] == 2) | (demographic['DMDMARTL'] == 3) | (demographic['DMDMARTL'] == 4)), 'Marital_Status_dummy'] = 2
demographic.loc[demographic['DMDMARTL'] == 5 , 'Marital_Status_dummy'] = 3

In [ ]:
demographic['Marital_Status_dummy'].value_counts()

1.00    3594
2.00    1396
3.00    1065
Name: Marital_Status_dummy, dtype: int64

In [ ]:
demographic.drop(columns = ['DMDMARTL'], inplace = True)

## Demographic: Education
- 1: Less than 9th grade
- 2: 9-11th grade(includes 12th grade with no diploma)
- 3: High school graduate/GED or equipment
- 4: some college or AA degreee
- 5: college graduate or above

In [ ]:
demographic['Education_dummy'] = demographic['DMDEDUC2']
demographic.loc[(demographic['DMDEDUC3'] < 9) | (demographic['DMDEDUC3'] == 66), 'Education_dummy'] = 1
demographic.loc[(demographic['DMDEDUC3'] > 9) & (demographic['DMDEDUC3'] < 13), 'Education_dummy'] = 2
demographic.loc[(demographic['DMDEDUC3'] == 14) | (demographic['DMDEDUC3'] == 13), 'Education_dummy'] = 3
demographic.loc[demographic['DMDEDUC3'] == 15, 'Education_dummy'] = 4

In [ ]:
demographic['Education_dummy'].replace({7: np.nan, 9:np.nan}, inplace = True)

In [ ]:
demographic['Education_dummy'].value_counts()

1.00    2523
4.00    1791
3.00    1488
2.00    1389
5.00    1230
Name: Education_dummy, dtype: int64

In [ ]:
demographic = demographic.drop(columns = ['DMDEDUC3', 'DMDEDUC2'])

## Income & Income_to_Proverty_Ratio
Income_to_Proverty_Ratio
- 1: less than 5 (proverty)
- 2: >= 5

In [ ]:
demographic['Income_dummy'] = demographic['INDFMIN2']
demographic.loc[demographic['INDFMIN2'] == 12, 'Income_dummy'] = 6
demographic.loc[demographic['INDFMIN2'] == 13, 'Income_dummy'] = 4
demographic.loc[demographic['INDFMIN2'] == 14, 'Income_dummy'] = 11
demographic.loc[demographic['INDFMIN2'] == 15, 'Income_dummy'] = 12
demographic['Income_dummy'].replace({77: np.nan, 99:np.nan}, inplace = True)

In [ ]:
demographic['Income_dummy'].value_counts()

 6.00    1649
12.00    1302
 5.00     891
 7.00     868
 4.00     858
11.00     829
 3.00     821
 8.00     752
 9.00     571
 2.00     500
10.00     380
 1.00     366
Name: Income_dummy, dtype: int64

In [ ]:
demographic.loc[demographic['INDFMPIR'] <= 1, 'Poverty_dummy'] = 1
demographic.loc[demographic['INDFMPIR'] > 1, 'Poverty_dummy'] = 0

In [ ]:
demographic.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10253 entries, 0 to 10536
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   SEQN                  10253 non-null  float64
 1   SDDSRVYR              10253 non-null  float64
 2   RIAGENDR              10253 non-null  float64
 3   RIDAGEYR              10253 non-null  float64
 4   RIDRETH1              10253 non-null  float64
 5   DMDBORN2              10253 non-null  float64
 6   DMDHREDU              10006 non-null  float64
 7   INDFMIN2              10203 non-null  float64
 8   INDFMPIR              9311 non-null   float64
 9   Marital_Status_dummy  6055 non-null   float64
 10  Education_dummy       8421 non-null   float64
 11  Income_dummy          9787 non-null   float64
 12  Poverty_dummy         9311 non-null   float64
dtypes: float64(13)
memory usage: 1.1 MB

In [ ]:
demographic['DMDBORN2'].replace({7: np.nan, 9:np.nan}, inplace = True)

In [ ]:
demographic.loc[demographic['DMDBORN2'] == 1, 'Country_of_birth_dummy'] = 1
demographic.loc[(demographic['DMDBORN2'] > 1) & (demographic['DMDBORN2'] < 7), 'Country_of_birth_dummy'] = 2

In [ ]:
demographic.rename(columns={'RIAGENDR': 'gender_dummy', 'RIDAGEYR': 'age', 'RIDRETH1': 'race_dummy', 'DMDHREDU': 'Household_reference_education_dummy'}, inplace = True)

In [ ]:
demographic.drop(columns = ['INDFMIN2', 'INDFMPIR', 'DMDBORN2'], inplace = True)

In [ ]:
demographic.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10253 entries, 0 to 10536
Data columns (total 11 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   SEQN                                 10253 non-null  float64
 1   SDDSRVYR                             10253 non-null  float64
 2   gender_dummy                         10253 non-null  float64
 3   age                                  10253 non-null  float64
 4   race_dummy                           10253 non-null  float64
 5   Household_reference_education_dummy  10006 non-null  float64
 6   Marital_Status_dummy                 6055 non-null   float64
 7   Education_dummy                      8421 non-null   float64
 8   Income_dummy                         9787 non-null   float64
 9   Poverty_dummy                        9311 non-null   float64
 10  Country_of_birth_dummy               10246 non-null  float64
dtypes: float64(11)
memory usage: 961.2 KB

In [ ]:
len(demographic.columns) == 11

True

In [ ]:
demographic.to_csv('cleaned_demographic.csv')

# Body Measure

In [ ]:
# read body measure file from Examination Data
body_measure = pd.read_sas(filepath_or_buffer = BASE_PATH + 'BMX.XPT')

# select columns
body_columns = ['SEQN', 'BMXWT', 'BMXHT', 'BMXBMI', 'BMXARMC', 'BMXWAIST']
body_measure = body_measure[body_columns]

# rename the columns
body_measure.rename(columns={'BMXWT': 'Weight(kg)', 'BMXHT': 'Height(cm)', 'BMXBMI': 'BMI', 'BMXARMC': 'Arm_Circumference', 'BMXWAIST': 'Waist_Circumference'}, inplace = True)

In [ ]:
body_measure.head()

,SEQN,Weight(kg),Height(cm),BMI,Arm_Circumference,Waist_Circumference
0,"51,624.00",87.40,164.70,32.22,36.40,100.40
1,"51,625.00",17.00,105.40,15.30,15.90,49.00
2,"51,626.00",72.30,181.30,22.00,26.60,74.70
3,"51,627.00",39.80,147.80,18.22,23.90,63.00
4,"51,628.00",116.80,166.00,42.39,42.20,118.20

In [ ]:
len(body_measure.columns) == 6

True

In [ ]:
body_measure.to_csv('cleaned_body_measure.csv')

# Other factors

## Consumer Behavior
The ratio is more important than the absolute value as the total spending amounts are different, therefore, the ratio is calcuated

In [ ]:
# read sas file
consumer = pd.read_sas(filepath_or_buffer = BASE_PATH + 'CBQ.XPT')

consumer_col = ['SEQN', 'CBD070', 'CBD090', 'CBD110', 'CBD120', 'CBD130']

consumer = consumer[consumer_col]

# get the ratio of each spending category
ratio_cal = consumer.iloc[:,1:].div(consumer.iloc[:,1:].sum(axis=1),axis=0)

ratio_cal['Spending_on_food'] = ratio_cal['CBD070'] + ratio_cal['CBD110']
ratio_cal.rename(columns = {'CBD090': 'Spending_on_nonfood', 'CBD120': 'Spending_on_eating_out', 'CBD130': 'Spending_on_carryout_deliverred'}, inplace = True)

consumer_final = pd.concat([consumer, ratio_cal], axis=1)
consumer_final = consumer_final.drop(columns = ['CBD070', 'CBD090', 'CBD110', 'CBD120', 'CBD130'])

In [ ]:
consumer_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10537 entries, 0 to 10536
Data columns (total 5 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   SEQN                             10537 non-null  float64
 1   Spending_on_nonfood              10419 non-null  float64
 2   Spending_on_eating_out           10427 non-null  float64
 3   Spending_on_carryout_deliverred  10427 non-null  float64
 4   Spending_on_food                 10427 non-null  float64
dtypes: float64(5)
memory usage: 411.7 KB

In [ ]:
print(len(consumer_final.columns) == 5)

True

In [ ]:
consumer_final.to_csv('cleaned_consumer_behavior.csv')

## Alcohol drink

In [ ]:
alcohol = pd.read_sas(filepath_or_buffer = BASE_PATH + 'ALQ.XPT')

In [ ]:
alcohol['ALQ120Q'].replace({777: np.nan, 999:np.nan}, inplace = True)

In [ ]:
alcohol[alcohol['ALQ120U'].isnull()]['ALQ120Q'].value_counts()

0.00    986
Name: ALQ120Q, dtype: int64

In [ ]:
alcohol.loc[alcohol['ALQ120Q'] < 0.01, 'alcohol_drink_frequency_dummy'] = 0
alcohol.loc[((alcohol['ALQ120Q'] <= 12) | (alcohol['ALQ120Q'] >= 1)) & (alcohol['ALQ120U'] == 3), 'alcohol_drink_frequency_dummy'] = 1
alcohol.loc[(alcohol['ALQ120Q'] == 1)  & (alcohol['ALQ120U'] == 2), 'alcohol_drink_frequency_dummy'] = 1
alcohol.loc[(~(alcohol['ALQ120Q'].isnull())) & (~(alcohol['ALQ120U'].isnull())) & (alcohol['alcohol_drink_frequency_dummy'].isnull()), 'alcohol_drink_frequency_dummy'] = 2

In [ ]:
alcohol[alcohol['alcohol_drink_frequency_dummy'].isnull()]['ALQ120Q'].value_counts()

Series([], Name: ALQ120Q, dtype: int64)

In [ ]:
alcohol.head()

,SEQN,ALQ101,ALQ110,ALQ120Q,ALQ120U,ALQ130,ALQ140Q,ALQ140U,ALQ150,alcohol_drink_frequency_dummy
0,"51,624.00",1.00,NaN,0.00,NaN,NaN,NaN,NaN,1.00,0.00
1,"51,628.00",2.00,1.00,0.00,NaN,NaN,NaN,NaN,2.00,0.00
2,"51,629.00",1.00,NaN,4.00,2.00,19.00,4.00,2.00,2.00,2.00
3,"51,630.00",1.00,NaN,20.00,3.00,2.00,0.00,NaN,2.00,1.00
4,"51,633.00",1.00,NaN,1.00,1.00,1.00,0.00,NaN,2.00,2.00

In [ ]:
alcohol.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6059 entries, 0 to 6058
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   SEQN                           6059 non-null   float64
 1   ALQ101                         5332 non-null   float64
 2   ALQ110                         1425 non-null   float64
 3   ALQ120Q                        4650 non-null   float64
 4   ALQ120U                        3664 non-null   float64
 5   ALQ130                         3666 non-null   float64
 6   ALQ140Q                        3666 non-null   float64
 7   ALQ140U                        1500 non-null   float64
 8   ALQ150                         4652 non-null   float64
 9   alcohol_drink_frequency_dummy  4650 non-null   float64
dtypes: float64(10)
memory usage: 473.5 KB

In [ ]:
alcohol.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6059 entries, 0 to 6058
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   SEQN                           6059 non-null   float64
 1   ALQ101                         5332 non-null   float64
 2   ALQ110                         1425 non-null   float64
 3   ALQ120Q                        4650 non-null   float64
 4   ALQ120U                        3664 non-null   float64
 5   ALQ130                         3666 non-null   float64
 6   ALQ140Q                        3666 non-null   float64
 7   ALQ140U                        1500 non-null   float64
 8   ALQ150                         4652 non-null   float64
 9   alcohol_drink_frequency_dummy  4650 non-null   float64
dtypes: float64(10)
memory usage: 473.5 KB

In [ ]:
alcohol['alcohol_drink_per_day'] = alcohol['ALQ130']
alcohol['alcohol_drink_per_day'].replace({777: np.nan, 999:np.nan}, inplace = True)

In [ ]:
alcohol_columns = ['SEQN', 'alcohol_drink_frequency_dummy', 'alcohol_drink_per_day']

In [ ]:
alcohol_final = alcohol[alcohol_columns]

In [ ]:
len(alcohol_final.columns) == 3

True

In [ ]:
alcohol_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6059 entries, 0 to 6058
Data columns (total 3 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   SEQN                           6059 non-null   float64
 1   alcohol_drink_frequency_dummy  4650 non-null   float64
 2   alcohol_drink_per_day          3664 non-null   float64
dtypes: float64(3)
memory usage: 142.1 KB

In [ ]:
alcohol_final.to_csv('cleaned_alcohol.csv')

## Diet behavior

In [ ]:
Diet_behavior = pd.read_sas(filepath_or_buffer = BASE_PATH + 'DBQ.XPT')

Diet_behavior_cols = ['SEQN', 'DBQ197', 'DBQ223A',  'DBQ223B', 'DBQ223C', 'DBQ223D', 'DBQ223E', 'DBQ223U', 'DBD895', 'DBD905', 'DBD910']
Diet_behavior = Diet_behavior[Diet_behavior_cols]

# get the milk type by assigning row-wise minimum value of all milk type columns
Diet_behavior['milk_type_dummy'] = Diet_behavior[['DBQ223A',  'DBQ223B', 'DBQ223C', 'DBQ223D', 'DBQ223E', 'DBQ223U']].min(axis=1)
Diet_behavior.loc[Diet_behavior['milk_type_dummy'] == 99, 'milk_type_dummy'] = np.nan


Diet_behavior.drop(columns = ['DBQ223A',  'DBQ223B', 'DBQ223C', 'DBQ223D', 'DBQ223E', 'DBQ223U'], inplace = True)

Diet_behavior['milk_product_consumption_freq_dummy'] = Diet_behavior['DBQ197']
Diet_behavior.loc[Diet_behavior['DBQ197'] == 4, 'milk_product_consumption_freq_dummy'] = 2

# number of meals not home prepared
Diet_behavior['eat_outside'] = Diet_behavior['DBD895']
Diet_behavior.loc[Diet_behavior['DBD895'] == 5555, 'eat_outside'] = 22
Diet_behavior.loc[Diet_behavior['DBD895'] > 5555, 'eat_outside'] = np.nan

# number of ready-to-eat foods in past 30 days
Diet_behavior['ready_to_eat_food'] = Diet_behavior['DBD905']
Diet_behavior.loc[Diet_behavior['DBD905'] == 6666, 'ready_to_eat_food'] = 100
Diet_behavior.loc[Diet_behavior['DBD905'] > 6666, 'ready_to_eat_food'] = np.nan

# of frozen meals/pizza in past 30 days
Diet_behavior['frozen_food'] = Diet_behavior['DBD910']
Diet_behavior.loc[Diet_behavior['DBD910'] == 6666, 'frozen_food'] = 100
Diet_behavior.loc[Diet_behavior['DBD910'] > 6666, 'frozen_food'] = np.nan

Diet_behavior.drop(columns = ['DBQ197', 'DBD895', 'DBD905', 'DBD910'], inplace = True)

In [ ]:
len(Diet_behavior.columns) == 6

True

In [ ]:
Diet_behavior.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10537 entries, 0 to 10536
Data columns (total 6 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   SEQN                                 10537 non-null  float64
 1   milk_type_dummy                      8947 non-null   float64
 2   milk_product_consumption_freq_dummy  10109 non-null  float64
 3   eat_outside                          10038 non-null  float64
 4   ready_to_eat_food                    10028 non-null  float64
 5   frozen_food                          10034 non-null  float64
dtypes: float64(6)
memory usage: 494.0 KB

In [ ]:
Diet_behavior.to_csv('cleaned_diet_behavior.csv')

## Mental Health

In [ ]:
mental_health = pd.read_sas(filepath_or_buffer = BASE_PATH + 'DPQ.XPT')

mental_health_cols = ['SEQN', 'DPQ030', 'DPQ040', 'DPQ050', 'DPQ060']
mental_health = mental_health[mental_health_cols]

mental_health_cols = ['DPQ030', 'DPQ040', 'DPQ050', 'DPQ060']

for col in mental_health_cols:
  mental_health.loc[(mental_health[col] < 1) , col + '_1'] = 'low'
  mental_health.loc[(mental_health[col] == 1) | (mental_health[col] == 2), col + '_1'] = 'mild'
  mental_health.loc[(mental_health[col] == 3) , col + '_1'] = 'severe'

mental_health = mental_health.rename(columns = {'DPQ030_1': 'trouble_sleeping_dummy', 'DPQ040_1': 'feeling_tired_dummy', 'DPQ050_1':'poor_appetite_dummy', 'DPQ060_1':'feeling_bad_dummy'})
mental_health.drop(columns=['DPQ030', 'DPQ040', 'DPQ050', 'DPQ060'], inplace = True)

In [ ]:
len(mental_health.columns) == 5

True

In [ ]:
mental_health.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6360 entries, 0 to 6359
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   SEQN                    6360 non-null   float64
 1   trouble_sleeping_dummy  5572 non-null   object
 2   feeling_tired_dummy     5569 non-null   object
 3   poor_appetite_dummy     5571 non-null   object
 4   feeling_bad_dummy       5564 non-null   object
dtypes: float64(1), object(4)
memory usage: 248.6+ KB

In [ ]:
mental_health.to_csv('cleaned_mental_health.csv')

## diabetes

In [ ]:
diabetes = pd.read_sas(filepath_or_buffer = BASE_PATH + 'DIQ.XPT')
diabetes.loc[(diabetes['DIQ010']==9),'DIQ010']=np.nan
diabetes.loc[(diabetes['DIQ050']==9),'DIQ010']=np.nan
diabetes.loc[(diabetes['DIQ160']==9),'DIQ010']=np.nan
diabetes=diabetes[['SEQN','DIQ010','DIQ050','DIQ160']]

dia_cols=['SEQN','have_diabetes_1_dummy','Taking_insulin_now_1_dummy','have_prediabetes_1_dummy']
diabetes.columns=dia_cols
clean_diabetes=diabetes

In [ ]:
clean_diabetes.to_csv('cleaned_diabetes.csv')

## Health Insurance

In [ ]:
insurance = pd.read_sas(filepath_or_buffer = BASE_PATH + 'HIQ.XPT')

insurance.loc[(insurance['HIQ011']==9),'HIQ011']=np.nan
insurance.loc[(insurance['HIQ011']==7),'HIQ011']=np.nan
insurance.loc[(insurance['HIQ270']==9),'HIQ270']=np.nan
insurance.loc[(insurance['HIQ270']==7),'HIQ270']=np.nan

insurance=insurance[['SEQN','HIQ011','HIQ270']]

insurance_cols=['SEQN','Covered_by_health_insurance_1_dummy','plans_cover_prescriptions_1_dummy']
insurance.columns=insurance_cols
clean_insurance=insurance

In [ ]:
clean_insurance.to_csv('cleaned_insurance.csv')

## Current_health_Status

In [ ]:
health_status = pd.read_sas(filepath_or_buffer = BASE_PATH + 'HSQ.XPT')

health_status.loc[(health_status['HSQ500']==9),'HSQ500']=np.nan
health_status.loc[(health_status['HSQ500']==7),'HSQ500']=np.nan
health_status.loc[(health_status['HSQ510']==9),'HSQ510']=np.nan
health_status.loc[(health_status['HSQ510']==7),'HSQ510']=np.nan
health_status.loc[(health_status['HSQ520']==9),'HSQ520']=np.nan
health_status=health_status[['SEQN','HSQ500','HSQ510','HSQ520']]

health_status_cols=['SEQN','head_cold_or_chest_cold_dummy','stomach_or_intestinal_illness_dummy','flu_pneumonia_ear_infection_dummy']
health_status.columns=health_status_cols

In [ ]:
health_status.to_csv('cleaned_health_status.csv')

## Occupation

In [ ]:
occupation = pd.read_sas(filepath_or_buffer = BASE_PATH + 'OCQ.XPT')

occupation=occupation[['SEQN','OCD150']]
occupation.loc[(occupation['OCD150']!=1),'OCD150']=0
occupation['OCD150'].value_counts()
occ_cols=['SEQN','have_job_1_dummy']
occupation.columns=occ_cols

In [ ]:
occupation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6889 entries, 0 to 6888
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   SEQN              6889 non-null   float64
 1   have_job_1_dummy  6889 non-null   float64
dtypes: float64(2)
memory usage: 107.8 KB

In [ ]:
occupation.to_csv('cleaned_occupation.csv')

## Medical Condition

In [ ]:
med_condition = pd.read_sas(filepath_or_buffer = BASE_PATH + 'MCQ.XPT')

med_condition=med_condition[['SEQN','MCQ010','MCQ053','MCQ092']]

med_condition.loc[(med_condition['MCQ010']==9),'MCQ010']=np.nan
med_condition.loc[(med_condition['MCQ053']==7),'MCQ053']=np.nan
med_condition.loc[(med_condition['MCQ053']==9),'MCQ053']=np.nan
med_condition.loc[(med_condition['MCQ092']==7),'MCQ092']=np.nan
med_condition.loc[(med_condition['MCQ092']==9),'MCQ092']=np.nan

med_cols=['SEQN','have_asthma_1_dummy','treatment_for_anemia_1_dummy','blood_transfusion_1_dummy']
med_condition.columns=med_cols

In [ ]:
med_condition.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10109 entries, 0 to 10108
Data columns (total 4 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   SEQN                          10109 non-null  float64
 1   have_asthma_1_dummy           10093 non-null  float64
 2   treatment_for_anemia_1_dummy  10102 non-null  float64
 3   blood_transfusion_1_dummy     8725 non-null   float64
dtypes: float64(4)
memory usage: 316.0 KB

In [ ]:
med_condition.to_csv('cleaned_med_condition.csv')

## Physical Activity

In [ ]:
physical_act = pd.read_sas(filepath_or_buffer = BASE_PATH + 'PAQ.XPT')

physical_act=physical_act[['SEQN','PAQ605','PAQ620','PAQ635','PAQ650','PAQ665']]
physical_act.loc[(physical_act['PAQ605']==9),'PAQ605']=np.nan
physical_act.loc[(physical_act['PAQ620']==9),'PAQ620']=np.nan

physical_act_cols=['SEQN','Vigorous_work_activity_1_dummy','Moderate work activity_1_dummy','Walk_or_bicycle_1_dummy','Vigorous_recreational_activities_1_dummy','Moderate_recreational_activities_1_dummy']
physical_act.columns=physical_act_cols

In [ ]:
physical_act.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9771 entries, 0 to 9770
Data columns (total 6 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   SEQN                                      9771 non-null   float64
 1   Vigorous_work_activity_1_dummy            7499 non-null   float64
 2   Moderate work activity_1_dummy            7499 non-null   float64
 3   Walk_or_bicycle_1_dummy                   7500 non-null   float64
 4   Vigorous_recreational_activities_1_dummy  7500 non-null   float64
 5   Moderate_recreational_activities_1_dummy  7500 non-null   float64
dtypes: float64(6)
memory usage: 458.1 KB

In [ ]:
physical_act.to_csv('cleaned_physical_act.csv')

## Sleeping disorder

In [ ]:
sleep_disorder = pd.read_sas(filepath_or_buffer = BASE_PATH + 'SLQ.XPT')


sleep_disorder.loc[(sleep_disorder['SLQ050']==9),'SLQ050']=np.nan

sleep_disorder=sleep_disorder[['SEQN', 'SLD010H', 'SLQ050']]
sleep_cols=['SEQN', 'Sleep_hours', 'had_trouble_sleeping_1_dummy']
sleep_disorder.columns=sleep_cols

In [ ]:
sleep_disorder.head()

                  SEQN          Sleep_hours  had_trouble_sleeping_1_dummy
0            51,624.00                 4.00                          1.00
1            51,626.00                 8.00                          2.00
2            51,628.00                 4.00                          2.00
3            51,629.00                 4.00                          2.00
4            51,630.00                 8.00                          1.00

In [ ]:
# # sleep hour
# sleep_disorder['hour'] = pd.to_numeric(sleep_disorder['Usual_sleep_time'].str[:2])
# sleep_disorder['min'] = pd.to_numeric(sleep_disorder['Usual_sleep_time'].str[3:])
# sleep_disorder = sleep_disorder[~(sleep_disorder['hour'] > 30)]
# sleep_disorder['min_decimal'] = sleep_disorder['min'] / 60
# sleep_disorder['final_sleep_time'] = sleep_disorder['hour'] + sleep_disorder['min_decimal']


# # Wake hour
# sleep_disorder['wake_hour'] = pd.to_numeric(sleep_disorder['Usual_wake_time'].str[:2])
# sleep_disorder['wake_min'] = pd.to_numeric(sleep_disorder['Usual_wake_time'].str[3:])
# sleep_disorder = sleep_disorder[~(sleep_disorder['wake_hour'] > 30)]
# sleep_disorder['wake_min_decimal'] = sleep_disorder['wake_min'] / 60
# sleep_disorder['final_wake_time'] = sleep_disorder['wake_hour'] + sleep_disorder['wake_min_decimal']

In [ ]:
sleep_disorder.columns

Index(['SEQN', 'Sleep_hours', 'had_trouble_sleeping_1_dummy'], dtype='object')

In [ ]:
# sleep_disorder.drop(columns = ['Usual_sleep_time', 'Usual_wake_time', 'hour', 'min', 'min_decimal',\
#                                'wake_hour', 'wake_min', 'wake_min_decimal'], inplace = True)

In [ ]:
# sleep_disorder.head()

In [ ]:
sleep_disorder.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6889 entries, 0 to 6888
Data columns (total 3 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   SEQN                          6889 non-null   float64
 1   Sleep_hours                   6882 non-null   float64
 2   had_trouble_sleeping_1_dummy  6886 non-null   float64
dtypes: float64(3)
memory usage: 161.6 KB

In [ ]:
sleep_disorder.to_csv('cleaned_sleep_disorder.csv')

## Smoking

In [ ]:
smoking = pd.read_sas(filepath_or_buffer = BASE_PATH + 'SMQ.XPT')

smoking=smoking[['SEQN','SMQ020']]
smoking_cols=['SEQN','>100_cigarettes_inlife_1_dummy']
smoking.columns=smoking_cols

In [ ]:
smoking.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7528 entries, 0 to 7527
Data columns (total 2 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   SEQN                            7528 non-null   float64
 1   >100_cigarettes_inlife_1_dummy  6218 non-null   float64
dtypes: float64(2)
memory usage: 117.8 KB

In [ ]:
smoking.to_csv('cleaned_smoking.csv')

## Smoking - Household Smokers

In [ ]:
# HH_smokers = pd.read_sas(filepath_or_buffer = BASE_PATH + 'SMQFAM.XPT')

# HH_smokers.loc[(HH_smokers['SMD460']==7.770000e+02),'SMD460']=np.nan
# HH_smokers.loc[(HH_smokers['SMD460']==9.990000e+02 ),'SMD460']=np.nan

# HH_smokers=HH_smokers[['SEQN','SMD460']]
# HH_smokers_cols=['SEQN','HH_smoke_number_dummy']
# HH_smokers.columns=HH_smokers_cols

KeyError: ignored

In [ ]:
# HH_smokers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10149 entries, 0 to 10148
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   SEQN     10149 non-null  float64
 1   SMD410   10072 non-null  float64
 2   SMD415   1840 non-null   float64
 3   SMD415A  1737 non-null   float64
 4   SMD430   1737 non-null   float64
dtypes: float64(5)
memory usage: 396.6 KB

In [ ]:
# HH_smokers.to_csv('cleaned_HH_smoker.csv')

# Diary Interview

In [ ]:
d1 = pd.read_sas(filepath_or_buffer = BASE_PATH + 'DR1TOT.XPT')
d1

/usr/local/lib/python3.7/dist-packages/pandas/io/sas/sas_xport.py:475: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  df[x] = v

,SEQN,WTDRD1,WTDR2D,DR1DRSTZ,DR1EXMER,DRABF,DRDINT,DR1DBIH,DR1DAY,DR1LANG,...,DRD370QQ,DRD370R,DRD370RQ,DRD370S,DRD370SQ,DRD370T,DRD370TQ,DRD370U,DRD370UQ,DRD370V
0,73557.0,1.688833e+04,12930.890649,1.0,49.0,2.0,2.0,6.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,73558.0,1.793214e+04,12684.148869,1.0,59.0,2.0,2.0,4.0,1.0,1.0,...,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0
2,73559.0,5.964181e+04,39394.236709,1.0,49.0,2.0,2.0,18.0,6.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,73560.0,1.422031e+05,125966.366442,1.0,54.0,2.0,2.0,21.0,3.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,73561.0,5.905236e+04,39004.892993,1.0,63.0,2.0,2.0,18.0,1.0,1.0,...,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9808,83727.0,1.414678e+04,10520.302070,1.0,59.0,2.0,2.0,8.0,7.0,1.0,...,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0
9809,83728.0,3.875076e+04,51815.103262,1.0,25.0,2.0,2.0,9.0,5.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9810,83729.0,1.527251e+04,10401.781170,1.0,59.0,2.0,2.0,1.0,6.0,1.0,...,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0
9811,83730.0,5.397605e-79,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9812,83731.0,5.805675e+03,4339.132077,1.0,49.0,2.0,2.0,12.0,6.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
d1['DRQSPREP'].value_counts()

4.0    3398
3.0    3078
2.0    1602
1.0     557
9.0     148
Name: DRQSPREP, dtype: int64

In [ ]:
d1.loc[(d1['WTDRD1']<0.01),'WTDRD1']=np.nan
d1.loc[(d1['WTDR2D']<0.01),'WTDR2D']=np.nan
d1.loc[(d1['DR1DRSTZ']==2),'DR1DRSTZ']=np.nan
d1.loc[(d1['DR1DRSTZ']==5),'DR1DRSTZ']=np.nan
d1.loc[(d1['DR1LANG']==3),'DR1LANG']=2
d1.loc[(d1['DR1LANG']==5),'DR1LANG']=4
d1.loc[(d1['DR1LANG']==6),'DR1LANG']=4
d1.loc[(d1['DBQ095Z']==99),'DBQ095Z']=np.nan
d1.loc[(d1['DBD100']==9),'DBD100']=np.nan
d1.loc[(d1['DRQSPREP']==9),'DRQSPREP']=np.nan
d1.loc[(d1['DR1STY']==9),'DR1STY']=np.nan

In [ ]:
d1=d1[['SEQN','WTDRD1','WTDR2D','DR1DRSTZ','DRABF','DR1LANG','DBQ095Z','DBD100','DRQSPREP','DRQSDIET']]
d1_cols=['SEQN','d1_sample_w','d2_sample_w','d_recall_status','Breast_fed_infant_1_dummy','language_dummy','salt_type_dummy','salt_freq_dummy','salt_inprep_dummy','special_diet_1_dummy']