In [15]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [6]:
%cd /content/drive/MyDrive/Hypertension_Final_Project

/content/drive/.shortcut-targets-by-id/1uEZ1Y_1ZZvyod9Tj5ozCHC79Wm5ucrk4/Hypertension_Final_Project

In [123]:
import pandas as pd
import numpy as np

In [104]:
BASE_PATH = "/content/drive/MyDrive/Hypertension_Final_Project/data_2017/"

#clean_diabetes

In [160]:
diabetes = pd.read_sas(filepath_or_buffer = BASE_PATH + 'DIQ_J.XPT')
diabetes

,SEQN,DIQ010,DID040,DIQ160,DIQ170,DIQ172,DIQ175A,DIQ175B,DIQ175C,DIQ175D,...,DIQ300D,DID310S,DID310D,DID320,DID330,DID341,DID350,DIQ350U,DIQ360,DIQ080
0,93703.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,93704.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,93705.0,2.0,NaN,2.0,2.0,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,93706.0,2.0,NaN,2.0,2.0,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,93707.0,2.0,NaN,2.0,2.0,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8892,102952.0,3.0,NaN,NaN,2.0,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8893,102953.0,2.0,NaN,1.0,2.0,1.0,NaN,11.0,NaN,13.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8894,102954.0,2.0,NaN,2.0,2.0,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8895,102955.0,2.0,NaN,2.0,2.0,1.0,NaN,11.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8896,102956.0,2.0,NaN,2.0,2.0,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [161]:
diabetes['DIQ010'].value_counts()
# diabetes=diabetes[diabetes['DIQ010']!=9.0]
# diabetes=diabetes[diabetes['DIQ050']!=9.0]
# diabetes=diabetes[diabetes['DIQ160']!=9.0]
#med_condition.loc[(med_condition['MCQ010']==9),'MCQ010']=np.nan
diabetes.loc[(diabetes['DIQ010']==9),'DIQ010']=np.nan
diabetes.loc[(diabetes['DIQ050']==9),'DIQ010']=np.nan
diabetes.loc[(diabetes['DIQ160']==9),'DIQ010']=np.nan
diabetes=diabetes[['SEQN','DIQ010','DIQ050','DIQ160']]
#diabetes=pd.get_dummies(diabetes,columns=['DIQ010','DIQ050','DIQ160'])
diabetes

          SEQN  DIQ010  DIQ050  DIQ160
0      93703.0     2.0     2.0     NaN
1      93704.0     2.0     2.0     NaN
2      93705.0     2.0     2.0     2.0
3      93706.0     2.0     2.0     2.0
4      93707.0     2.0     2.0     2.0
...        ...     ...     ...     ...
8892  102952.0     3.0     2.0     NaN
8893  102953.0     2.0     2.0     1.0
8894  102954.0     2.0     2.0     2.0
8895  102955.0     2.0     2.0     2.0
8896  102956.0     2.0     2.0     2.0

[8897 rows x 4 columns]

In [162]:
dia_cols=['SEQN','have_diabetes_1_dummy','Taking_insulin_now_1_dummy','have_prediabetes_1_dummy']

In [163]:
diabetes.columns=dia_cols
clean_diabetes=diabetes
clean_diabetes.to_csv('clean_diabetes.csv')

In [164]:
clean_diabetes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8897 entries, 0 to 8896
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   SEQN                        8897 non-null   float64
 1   have_diabetes_1_dummy       8885 non-null   float64
 2   Taking_insulin_now_1_dummy  8897 non-null   float64
 3   have_prediabetes_1_dummy    5694 non-null   float64
dtypes: float64(4)
memory usage: 278.2 KB

#Health Insurance

In [165]:
insurance = pd.read_sas(filepath_or_buffer = BASE_PATH + 'HIQ_J.XPT')
insurance

,SEQN,HIQ011,HIQ031A,HIQ031B,HIQ031C,HIQ031D,HIQ031E,HIQ031F,HIQ031H,HIQ031I,HIQ031J,HIQ031AA,HIQ260,HIQ105,HIQ270,HIQ210
0,93703.0,1.0,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
1,93704.0,1.0,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
2,93705.0,1.0,NaN,15.0,NaN,17.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,2.0
3,93706.0,1.0,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
4,93707.0,1.0,NaN,NaN,NaN,17.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9249,102952.0,1.0,14.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,2.0
9250,102953.0,1.0,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0
9251,102954.0,1.0,NaN,NaN,NaN,17.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
9252,102955.0,1.0,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0
9253,102956.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,21.0,NaN,NaN,NaN,NaN,NaN,1.0,2.0

In [166]:
# insurance=insurance[insurance['HIQ011']!=9]
# insurance=insurance[insurance['HIQ011']!=7]
# insurance=insurance[insurance['HIQ270']!=9]
# insurance=insurance[insurance['HIQ270']!=7]
insurance.loc[(insurance['HIQ011']==9),'HIQ011']=np.nan
insurance.loc[(insurance['HIQ011']==7),'HIQ011']=np.nan
insurance.loc[(insurance['HIQ270']==9),'HIQ270']=np.nan
insurance.loc[(insurance['HIQ270']==7),'HIQ270']=np.nan
insurance['HIQ270'].value_counts()
insurance=insurance[['SEQN','HIQ011','HIQ270']]
#insurance=pd.get_dummies(insurance,columns=['HIQ011','HIQ270'])
insurance

          SEQN  HIQ011  HIQ270
0      93703.0     1.0     1.0
1      93704.0     1.0     1.0
2      93705.0     1.0     1.0
3      93706.0     1.0     1.0
4      93707.0     1.0     1.0
...        ...     ...     ...
9249  102952.0     1.0     1.0
9250  102953.0     1.0     1.0
9251  102954.0     1.0     1.0
9252  102955.0     1.0     1.0
9253  102956.0     1.0     1.0

[9254 rows x 3 columns]

In [167]:
insurance_cols=['SEQN','Covered_by_health_insurance_1_dummy','plans_cover_prescriptions_1_dummy']

In [168]:
insurance.columns=insurance_cols
clean_insurance=insurance
clean_insurance.to_csv('clean_insurance.csv')
clean_insurance

,SEQN,Covered_by_health_insurance_1_dummy,plans_cover_prescriptions_1_dummy
0,93703.0,1.0,1.0
1,93704.0,1.0,1.0
2,93705.0,1.0,1.0
3,93706.0,1.0,1.0
4,93707.0,1.0,1.0
...,...,...,...
9249,102952.0,1.0,1.0
9250,102953.0,1.0,1.0
9251,102954.0,1.0,1.0
9252,102955.0,1.0,1.0
9253,102956.0,1.0,1.0

In [169]:
clean_insurance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9254 entries, 0 to 9253
Data columns (total 3 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   SEQN                                 9254 non-null   float64
 1   Covered_by_health_insurance_1_dummy  9229 non-null   float64
 2   plans_cover_prescriptions_1_dummy    8057 non-null   float64
dtypes: float64(3)
memory usage: 217.0 KB

#Current_health_Status

In [171]:
health_status = pd.read_sas(filepath_or_buffer = BASE_PATH + 'HSQ_J.XPT')
health_status

,SEQN,HSD010,HSQ500,HSQ510,HSQ520,HSQ571,HSQ580,HSQ590,HSAQUEX
0,93703.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1,93704.0,NaN,2.0,2.0,2.0,NaN,NaN,NaN,1.0
2,93705.0,3.0,2.0,2.0,2.0,2.0,NaN,1.0,2.0
3,93706.0,2.0,2.0,2.0,2.0,1.0,5.0,2.0,2.0
4,93707.0,3.0,2.0,2.0,2.0,NaN,NaN,NaN,2.0
...,...,...,...,...,...,...,...,...,...
8361,102952.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0
8362,102953.0,4.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0
8363,102954.0,3.0,2.0,2.0,2.0,2.0,NaN,1.0,2.0
8364,102955.0,2.0,1.0,2.0,2.0,NaN,NaN,NaN,2.0
8365,102956.0,3.0,2.0,2.0,2.0,2.0,NaN,1.0,2.0

In [172]:
# health_status=health_status[health_status['HSQ500']!=9]
# health_status=health_status[health_status['HSQ500']!=7]
# health_status=health_status[health_status['HSQ510']!=9]
# health_status=health_status[health_status['HSQ510']!=7]
# health_status=health_status[health_status['HSQ520']!=9]
health_status.loc[(health_status['HSQ500']==9),'HSQ500']=np.nan
health_status.loc[(health_status['HSQ500']==7),'HSQ500']=np.nan
health_status.loc[(health_status['HSQ510']==9),'HSQ510']=np.nan
health_status.loc[(health_status['HSQ510']==7),'HSQ510']=np.nan
health_status.loc[(health_status['HSQ520']==9),'HSQ520']=np.nan
health_status=health_status[['SEQN','HSQ500','HSQ510','HSQ520']]
health_status['HSQ500'].value_counts()
health_status.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8366 entries, 0 to 8365
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   SEQN    8366 non-null   float64
 1   HSQ500  7491 non-null   float64
 2   HSQ510  7512 non-null   float64
 3   HSQ520  7527 non-null   float64
dtypes: float64(4)
memory usage: 261.6 KB

In [173]:
health_status_cols=['SEQN','head_cold_or_chest_cold_dummy','stomach_or_intestinal_illness_dummy','flu_pneumonia_ear_infection_dummy']
health_status.columns=health_status_cols

In [174]:
health_status.to_csv('clean_health_status.csv')
health_status

,SEQN,head_cold_or_chest_cold_dummy,stomach_or_intestinal_illness_dummy,flu_pneumonia_ear_infection_dummy
0,93703.0,NaN,NaN,NaN
1,93704.0,2.0,2.0,2.0
2,93705.0,2.0,2.0,2.0
3,93706.0,2.0,2.0,2.0
4,93707.0,2.0,2.0,2.0
...,...,...,...,...
8361,102952.0,2.0,2.0,2.0
8362,102953.0,2.0,2.0,2.0
8363,102954.0,2.0,2.0,2.0
8364,102955.0,1.0,2.0,2.0
8365,102956.0,2.0,2.0,2.0

#Occupation

In [175]:
occupation = pd.read_sas(filepath_or_buffer = BASE_PATH + 'OCQ_J.XPT')
occupation

,SEQN,OCD150,OCQ180,OCQ210,OCQ260,OCD270,OCQ670,OCQ380,OCD390G,OCD395
0,93705.0,1.0,30.0,1.0,1.0,36.0,5.0,NaN,2.0,NaN
1,93706.0,4.0,NaN,NaN,NaN,NaN,NaN,2.0,4.0,NaN
2,93708.0,4.0,NaN,NaN,NaN,NaN,NaN,4.0,1.0,180.0
3,93709.0,4.0,NaN,NaN,NaN,NaN,NaN,6.0,1.0,360.0
4,93711.0,1.0,35.0,NaN,4.0,24.0,1.0,NaN,2.0,NaN
...,...,...,...,...,...,...,...,...,...,...
6156,102950.0,1.0,70.0,NaN,3.0,120.0,2.0,NaN,2.0,NaN
6157,102952.0,4.0,NaN,NaN,NaN,NaN,NaN,3.0,1.0,168.0
6158,102953.0,1.0,42.0,NaN,1.0,204.0,5.0,NaN,1.0,216.0
6159,102954.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,120.0
6160,102956.0,4.0,NaN,NaN,NaN,NaN,NaN,4.0,1.0,120.0

In [176]:
occupation=occupation[['SEQN','OCD150']]
occupation.loc[(occupation['OCD150']!=1),'OCD150']=0
occupation['OCD150'].value_counts()
occ_cols=['SEQN','have_job_1_dummy']
occupation.columns=occ_cols
occupation.info()
occupation.to_csv('clean_occupation.csv')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6161 entries, 0 to 6160
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   SEQN              6161 non-null   float64
 1   have_job_1_dummy  6161 non-null   float64
dtypes: float64(2)
memory usage: 96.4 KB

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:723: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value, self.name)

In [177]:
occupation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6161 entries, 0 to 6160
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   SEQN              6161 non-null   float64
 1   have_job_1_dummy  6161 non-null   float64
dtypes: float64(2)
memory usage: 96.4 KB

#Medical Condition

In [178]:
med_condition = pd.read_sas(filepath_or_buffer = BASE_PATH + 'MCQ_J.XPT')
med_condition

,SEQN,MCQ010,MCQ025,MCQ035,MCQ040,MCQ050,AGQ030,MCQ053,MCQ080,MCQ092,...,MCQ300A,MCQ366A,MCQ366B,MCQ366C,MCQ366D,MCQ371A,MCQ371B,MCQ371C,MCQ371D,OSQ230
0,93703.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,93704.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,93705.0,1.0,10.0,2.0,NaN,NaN,NaN,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0
3,93706.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,...,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN
4,93707.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8892,102952.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0
8893,102953.0,1.0,42.0,1.0,1.0,2.0,1.0,2.0,1.0,2.0,...,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0
8894,102954.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,1.0,2.0,...,2.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0
8895,102955.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8896,102956.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,1.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN

In [179]:
med_condition=med_condition[['SEQN','MCQ010','MCQ053','MCQ092']]
med_condition['MCQ010'].value_counts()

2.0    7563
1.0    1325
9.0       9
Name: MCQ010, dtype: int64

In [121]:
'''
med_condition=med_condition[med_condition['MCQ010']!=9]
med_condition=med_condition[med_condition['MCQ053']!=7]
med_condition=med_condition[med_condition['MCQ053']!=9]
med_condition=med_condition[med_condition['MCQ092']!=7]
med_condition=med_condition[med_condition['MCQ092']!=9]
med_condition.info()
'''

"\nmed_condition=med_condition[med_condition['MCQ010']!=9]\nmed_condition=med_condition[med_condition['MCQ053']!=7]\nmed_condition=med_condition[med_condition['MCQ053']!=9]\nmed_condition=med_condition[med_condition['MCQ092']!=7]\nmed_condition=med_condition[med_condition['MCQ092']!=9]\nmed_condition.info()\n"

In [180]:
#occupation.loc[(occupation['OCD150']!=1),'OCD150']=0
med_condition.loc[(med_condition['MCQ010']==9),'MCQ010']=np.nan
med_condition.loc[(med_condition['MCQ053']==7),'MCQ053']=np.nan
med_condition.loc[(med_condition['MCQ053']==9),'MCQ053']=np.nan
med_condition.loc[(med_condition['MCQ092']==7),'MCQ092']=np.nan
med_condition.loc[(med_condition['MCQ092']==9),'MCQ092']=np.nan

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:723: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value, self.name)

In [181]:
med_condition['MCQ092'].value_counts()

2.0    7107
1.0     689
Name: MCQ092, dtype: int64

In [182]:
med_cols=['SEQN','have_asthma_1_dummy','treatment_for_anemia_1_dummy','blood_transfusion_1_dummy']
med_condition.columns=med_cols
med_condition.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8897 entries, 0 to 8896
Data columns (total 4 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   SEQN                          8897 non-null   float64
 1   have_asthma_1_dummy           8888 non-null   float64
 2   treatment_for_anemia_1_dummy  8882 non-null   float64
 3   blood_transfusion_1_dummy     7796 non-null   float64
dtypes: float64(4)
memory usage: 278.2 KB

In [183]:
med_condition.to_csv('clean_med_condition.csv')

#Physical Activity

In [184]:
physical_act = pd.read_sas(filepath_or_buffer = BASE_PATH + 'PAQ_J.XPT')
physical_act

,SEQN,PAQ605,PAQ610,PAD615,PAQ620,PAQ625,PAD630,PAQ635,PAQ640,PAD645,PAQ650,PAQ655,PAD660,PAQ665,PAQ670,PAD675,PAD680
0,93705.0,2.0,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,1.0,2.0,60.0,300.0
1,93706.0,2.0,NaN,NaN,2.0,NaN,NaN,1.0,5.0,45.0,2.0,NaN,NaN,1.0,2.0,30.0,240.0
2,93708.0,2.0,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,1.0,5.0,30.0,120.0
3,93709.0,2.0,NaN,NaN,1.0,2.0,180.0,2.0,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,600.0
4,93711.0,2.0,NaN,NaN,2.0,NaN,NaN,1.0,5.0,60.0,1.0,4.0,60.0,1.0,2.0,30.0,420.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5851,102950.0,2.0,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,60.0
5852,102952.0,2.0,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,1.0,6.0,60.0,120.0
5853,102953.0,1.0,3.0,240.0,1.0,3.0,240.0,2.0,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,360.0
5854,102954.0,2.0,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,1.0,2.0,30.0,600.0
5855,102956.0,2.0,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,720.0

In [193]:
physical_act=physical_act[['SEQN','PAQ605','PAQ620','PAQ635','PAQ650','PAQ665']]
physical_act.loc[(physical_act['PAQ605']==9),'PAQ605']=np.nan
physical_act.loc[(physical_act['PAQ620']==9),'PAQ620']=np.nan
physical_act['PAQ665'].value_counts()

2.0    3548
1.0    2308
Name: PAQ665, dtype: int64

In [194]:
physical_act_cols=['SEQN','Vigorous_work_activity_1_dummy','Moderate work activity_1_dummy','Walk_or_bicycle_1_dummy','Vigorous_recreational_activities_1_dummy','Moderate_recreational_activities_1_dummy']
physical_act.columns=physical_act_cols
physical_act

,SEQN,Vigorous_work_activity_1_dummy,Moderate work activity_1_dummy,Walk_or_bicycle_1_dummy,Vigorous_recreational_activities_1_dummy,Moderate_recreational_activities_1_dummy
0,93705.0,2.0,2.0,2.0,2.0,1.0
1,93706.0,2.0,2.0,1.0,2.0,1.0
2,93708.0,2.0,2.0,2.0,2.0,1.0
3,93709.0,2.0,1.0,2.0,2.0,2.0
4,93711.0,2.0,2.0,1.0,1.0,1.0
...,...,...,...,...,...,...
5851,102950.0,2.0,2.0,2.0,2.0,2.0
5852,102952.0,2.0,2.0,2.0,2.0,1.0
5853,102953.0,1.0,1.0,2.0,2.0,2.0
5854,102954.0,2.0,2.0,2.0,2.0,1.0
5855,102956.0,2.0,2.0,2.0,2.0,2.0

In [195]:
physical_act.to_csv('physical_act.csv')

#Sleeping disorder

In [243]:
sleep_disorder = pd.read_sas(filepath_or_buffer = BASE_PATH + 'SLQ_J.XPT')
sleep_disorder

,SEQN,SLQ300,SLQ310,SLD012,SLQ320,SLQ330,SLD013,SLQ030,SLQ040,SLQ050,SLQ120
0,93705.0,b'23:00',b'07:00',8.0,b'23:00',b'07:00',8.0,2.000000e+00,5.397605e-79,2.0,5.397605e-79
1,93706.0,b'23:30',b'10:00',10.5,b'00:30',b'12:00',11.5,1.000000e+00,5.397605e-79,2.0,1.000000e+00
2,93708.0,b'22:30',b'06:30',8.0,b'22:30',b'06:30',8.0,9.000000e+00,5.397605e-79,2.0,2.000000e+00
3,93709.0,b'22:30',b'05:30',7.0,b'22:30',b'05:00',6.5,1.000000e+00,5.397605e-79,2.0,1.000000e+00
4,93711.0,b'22:00',b'05:00',7.0,b'23:00',b'08:00',9.0,2.000000e+00,1.000000e+00,1.0,3.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
6156,102950.0,b'03:00',b'10:00',7.0,b'22:00',b'09:00',11.0,1.000000e+00,1.000000e+00,2.0,2.000000e+00
6157,102952.0,b'22:30',b'07:00',8.5,b'22:30',b'07:00',8.5,5.397605e-79,5.397605e-79,2.0,5.397605e-79
6158,102953.0,b'22:00',b'04:00',6.0,b'23:00',b'04:00',5.0,5.397605e-79,1.000000e+00,1.0,2.000000e+00
6159,102954.0,b'22:00',b'06:00',8.0,b'00:00',b'07:00',7.0,1.000000e+00,5.397605e-79,2.0,1.000000e+00
6160,102956.0,b'23:00',b'07:00',8.0,b'02:00',b'09:00',7.0,5.397605e-79,5.397605e-79,1.0,1.000000e+00

In [244]:
sleep_disorder.loc[(sleep_disorder['SLQ030']==9),'SLQ030']=np.nan
sleep_disorder.loc[(sleep_disorder['SLQ030']==7),'SLQ030']=np.nan
sleep_disorder.loc[(sleep_disorder['SLQ310']==9),'SLQ310']=np.nan
sleep_disorder.loc[(sleep_disorder['SLQ310']==7),'SLQ310']=np.nan
sleep_disorder.loc[(sleep_disorder['SLQ050']==9),'SLQ050']=np.nan
sleep_disorder.loc[(sleep_disorder['SLQ120']==9),'SLQ120']=np.nan

In [245]:
sleep_disorder=sleep_disorder[['SEQN','SLQ300','SLQ310','SLD012','SLQ030','SLQ050','SLQ120']]
sleep_cols=['SEQN','Usual_sleep_time','Usual_wake_time','Sleep_hours','snore_freq_dummy','had_trouble_sleeping_1_dummy','overly_sleepy_during_day_dummy']

In [248]:
sleep_disorder.columns=sleep_cols
sleep_disorder['Usual_sleep_time'].value_counts()

b'23:00'    1264
b'22:00'    1216
b'00:00'     801
b'21:00'     557
b'22:30'     409
b'01:00'     308
b'23:30'     281
b'21:30'     236
b'02:00'     218
b'20:00'     169
b'03:00'      97
b'00:30'      73
b'20:30'      66
b'04:00'      44
b'01:30'      38
b'19:00'      37
b''           37
b'99999'      36
b'08:00'      29
b'09:00'      23
b'05:00'      21
b'02:30'      19
b'06:00'      17
b'10:00'      16
b'07:00'      16
b'18:00'      15
b'19:30'      14
b'12:00'       9
b'08:30'       7
b'17:00'       7
b'11:00'       7
b'22:45'       7
b'07:30'       6
b'16:00'       5
b'03:30'       5
b'21:45'       5
b'06:30'       4
b'18:30'       4
b'23:15'       4
b'04:30'       4
b'14:00'       3
b'22:15'       3
b'10:30'       3
b'09:30'       2
b'21:15'       2
b'05:30'       2
b'23:45'       2
b'22:10'       1
b'03:45'       1
b'13:30'       1
b'13:00'       1
b'00:15'       1
b'21:50'       1
b'23:40'       1
b'15:00'       1
b'21:40'       1
b'77777'       1
b'09:45'       1
b'21:10'       1
b'20:45'       1
Name: Usual_sleep_time, dtype: int64

In [ ]:
sleep_disorder.to_csv('clean_sleep_disorder.csv')

#Smoking

In [220]:
smoking = pd.read_sas(filepath_or_buffer = BASE_PATH + 'SMQ_J.XPT')
smoking

,SEQN,SMQ020,SMD030,SMQ040,SMQ050Q,SMQ050U,SMD057,SMQ078,SMD641,SMD650,...,SMQ848,SMQ852Q,SMQ852U,SMQ890,SMQ895,SMQ900,SMQ905,SMQ910,SMQ915,SMAQUEX2
0,93705.0,1.0,16.0,3.0,30.0,4.0,5.0,NaN,NaN,NaN,...,NaN,NaN,NaN,2.0,NaN,2.0,NaN,2.0,NaN,1.0
1,93706.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2.0,NaN,2.0,NaN,2.0,NaN,1.0
2,93707.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
3,93708.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2.0,NaN,2.0,NaN,2.0,NaN,1.0
4,93709.0,1.0,15.0,1.0,NaN,NaN,NaN,1.0,30.0,5.0,...,NaN,NaN,NaN,1.0,5.397605e-79,1.0,5.397605e-79,1.0,5.397605e-79,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6719,102952.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2.0,NaN,2.0,NaN,2.0,NaN,1.0
6720,102953.0,1.0,20.0,3.0,9.0,3.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,1.0,5.397605e-79,1.0,5.397605e-79,1.0,5.397605e-79,1.0
6721,102954.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2.0,NaN,2.0,NaN,2.0,NaN,1.0
6722,102955.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
6723,102956.0,1.0,16.0,1.0,NaN,NaN,NaN,2.0,30.0,20.0,...,1.0,2.0,1.0,2.0,NaN,2.0,NaN,1.0,5.397605e-79,1.0

In [226]:
smoking.loc[(smoking['SMQ890']==9),'SMQ890']=np.nan
smoking=smoking[['SEQN','SMQ020','SMQ890','SMAQUEX2']]
smoking_cols=['SEQN','>100_cigarettes_inlife_1_dummy','smoked>1_1_dummy','Home_Interview_(18+ Yrs)_1_dummy']

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:723: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value, self.name)

In [228]:
smoking.columns=smoking_cols
smoking.to_csv('clean_smoking.csv')

#SMQFAM_j

In [239]:
HH_smokers = pd.read_sas(filepath_or_buffer = BASE_PATH + 'SMQFAM_J.XPT')
HH_smokers

          SEQN        SMD460        SMD470  SMD480
0      93703.0  5.397605e-79           NaN     NaN
1      93704.0  5.397605e-79           NaN     NaN
2      93705.0  5.397605e-79           NaN     NaN
3      93706.0           NaN           NaN     NaN
4      93707.0  1.000000e+00  1.000000e+00     5.0
...        ...           ...           ...     ...
9249  102952.0  5.397605e-79           NaN     NaN
9250  102953.0  5.397605e-79           NaN     NaN
9251  102954.0  5.397605e-79           NaN     NaN
9252  102955.0  2.000000e+00  5.397605e-79     NaN
9253  102956.0  1.000000e+00  5.397605e-79     NaN

[9254 rows x 4 columns]

In [240]:
HH_smokers.loc[(HH_smokers['SMD460']==7.770000e+02),'SMD460']=np.nan
HH_smokers.loc[(HH_smokers['SMD460']==9.990000e+02 ),'SMD460']=np.nan

HH_smokers['SMD460'].value_counts()

5.397605e-79    6092
1.000000e+00    1667
2.000000e+00     867
3.000000e+00     153
Name: SMD460, dtype: int64

In [241]:
HH_smokers=HH_smokers[['SEQN','SMD460']]
HH_smokers_cols=['SEQN','HH_smoke_number_dummy']
HH_smokers.columns=HH_smokers_cols
HH_smokers.to_csv('clean_HH_smoker.csv')

In [8]:
age_group=pd.read_csv('age_group.csv')
age_group

      Unnamed: 0      SEQN   age
0              0   93703.0   2.0
1              1   93704.0   2.0
2              2   93705.0  66.0
3              3   93706.0  18.0
4              4   93707.0  13.0
...          ...       ...   ...
8696        9249  102952.0  70.0
8697        9250  102953.0  42.0
8698        9251  102954.0  41.0
8699        9252  102955.0  14.0
8700        9253  102956.0  38.0

[8701 rows x 3 columns]

In [9]:
cleaned_blood_pressure=pd.read_csv('cleaned_blood_pressure.csv')
cleaned_blood_pressure

      Unnamed: 0      SEQN  Systolic_BP  Diastolic_BP
0              0   93703.0          NaN           NaN
1              1   93704.0          NaN           NaN
2              2   93705.0   200.000000     68.000000
3              3   93706.0   111.333333     73.333333
4              4   93707.0   128.000000     47.333333
...          ...       ...          ...           ...
8699        8699  102952.0   139.333333     73.333333
8700        8700  102953.0   120.666667     75.333333
8701        8701  102954.0   116.000000     70.666667
8702        8702  102955.0   114.000000     62.000000
8703        8703  102956.0   148.000000     96.000000

[8704 rows x 4 columns]

In [11]:
cleaned_body_measure=pd.read_csv('cleaned_body_measure.csv')
cleaned_body_measure

,Unnamed: 0,SEQN,Weight(kg),Height(cm),BMI,Arm_Circumference,Waist_Circumference,Hip_Circumference,age
0,0,93703.0,13.7,88.6,17.5,16.2,48.2,NaN,2.0
1,1,93704.0,13.9,94.2,15.7,15.2,50.0,NaN,2.0
2,2,93705.0,79.5,158.3,31.7,32.0,101.8,110.0,66.0
3,3,93706.0,66.3,175.7,21.5,27.0,79.3,94.4,18.0
4,4,93707.0,45.4,158.4,18.1,21.5,64.1,83.0,13.0
...,...,...,...,...,...,...,...,...,...
8696,8696,102952.0,49.0,156.5,20.0,25.1,82.2,87.3,70.0
8697,8697,102953.0,97.4,164.9,35.8,40.6,114.8,112.8,42.0
8698,8698,102954.0,69.1,162.6,26.1,26.8,86.4,102.7,41.0
8699,8699,102955.0,111.9,156.6,45.6,44.5,113.5,128.3,14.0
8700,8700,102956.0,111.5,175.8,36.1,40.0,122.0,110.0,38.0

In [12]:
cleaned_demographic=pd.read_csv('cleaned_demographic.csv')
cleaned_demographic

,Unnamed: 0,SEQN,SDDSRVYR,age,Female,Other_Hispanic,White,Black,Asian,Other_Race,...,Income_4.0,Income_5.0,Income_6.0,Income_7.0,Income_8.0,Income_9.0,Income_10.0,Income_11.0,Income_12.0,proverty
0,0,93703.0,10.0,2.0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
1,1,93704.0,10.0,2.0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,2,93705.0,10.0,66.0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
3,3,93706.0,10.0,18.0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
4,4,93707.0,10.0,13.0,0,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8696,9249,102952.0,10.0,70.0,1,0,0,0,1,0,...,1,0,0,0,0,0,0,0,0,1
8697,9250,102953.0,10.0,42.0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
8698,9251,102954.0,10.0,41.0,1,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
8699,9252,102955.0,10.0,14.0,1,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
8700,9253,102956.0,10.0,38.0,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [13]:
cleaned_Hypertension_Questionnaire=pd.read_csv('cleaned_Hypertension_Questionnaire.csv')
cleaned_Hypertension_Questionnaire

,Unnamed: 0,SEQN,BPQ020,BPQ050A,Told_High_blood_pressure,Taking_Medicine_for_HBP
0,0,93705.0,1.0,1.0,1.0,1.0
1,1,93706.0,2.0,NaN,0.0,0.0
2,2,93708.0,1.0,1.0,1.0,1.0
3,3,93709.0,1.0,1.0,1.0,1.0
4,4,93711.0,2.0,NaN,0.0,0.0
...,...,...,...,...,...,...
6156,6156,102950.0,1.0,1.0,1.0,1.0
6157,6157,102952.0,2.0,NaN,0.0,0.0
6158,6158,102953.0,2.0,NaN,0.0,0.0
6159,6159,102954.0,2.0,NaN,0.0,0.0
6160,6160,102956.0,1.0,NaN,1.0,0.0

In [14]:
consumer_behavior=pd.read_csv('consumer_behavior.csv')
consumer_behavior

,Unnamed: 0,SEQN,Spending_on_nonfood,Spending_on_eating_out,Spending_on_carryout_deliverred,Spending_on_food,age
0,0,93703.0,7.393980e-82,0.273973,4.109589e-02,0.684932,2.0
1,1,93704.0,2.985075e-02,0.049751,2.487562e-02,0.895522,2.0
2,2,93705.0,1.914044e-81,0.265957,3.794326e-01,0.354610,66.0
3,3,93706.0,NaN,NaN,NaN,NaN,18.0
4,4,93707.0,7.401925e-02,0.074019,3.700962e-02,0.814952,13.0
...,...,...,...,...,...,...,...
8696,8696,102952.0,1.298701e-01,0.155844,7.009877e-82,0.714286,70.0
8697,8697,102953.0,9.338418e-82,0.346021,9.338418e-82,0.653979,42.0
8698,8698,102954.0,5.742133e-82,0.212766,4.255319e-02,0.744681,41.0
8699,8699,102955.0,3.472222e-02,0.069444,2.777778e-02,0.868056,14.0
8700,8700,102956.0,1.142857e-01,0.114286,3.084346e-82,0.771429,38.0

#Merge tables